# Generated by Django 4.0.4 on 2022-06-04 13:50

import apps.responsible_disc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0019_delete_vulnerabilityreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (2, 'Vendor Notified'), (3, 'Vendor Acknowledged'), (1, 'Fixed')], default=0)),
                ('severity', models.PositiveIntegerField(choices=[(4, 'Critical'), (3, 'High'), (2, 'Medium'), (1, 'Low'), (0, 'Informational')])),
                ('vendor', models.CharField(max_length=128)),
                ('vendor_homepage', models.URLField()),
                ('affected_product', models.CharField(max_length=256)),
                ('affected_versions', models.CharField(max_length=256)),
                ('fixed_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cve_id', models.CharField(blank=True, max_length=32, null=True)),
                ('cve_request_id', models.CharField(blank=True, max_length=32, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_vulnerability_set', to='findings.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_vulnerability_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('text', models.TextField(help_text='Markdown supported!')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsible_disc.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(max_length=256, upload_to=apps.responsible_disc.models.get_proof_path)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsible_disc.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
