# Generated by Django 4.0.5 on 2022-06-16 07:09

import apps.responsible_disc.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('severity', models.PositiveIntegerField(blank=True, choices=[(4, 'Critical'), (3, 'High'), (2, 'Medium'), (1, 'Low'), (0, 'Informational')], null=True)),
                ('vendor', models.CharField(max_length=128)),
                ('vendor_homepage', models.URLField()),
                ('vendor_email', models.EmailField(max_length=254, null=True)),
                ('affected_product', models.CharField(max_length=256)),
                ('affected_versions', models.CharField(max_length=256)),
                ('fixed_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cve_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='CVE-ID')),
                ('cve_request_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='CVE Request ID')),
                ('is_published', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_vulnerability_set', to='findings.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resp_vulnerability_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('custom_date', models.DateTimeField(blank=True, null=True)),
                ('action', models.PositiveIntegerField(choices=[(1, 'Notified vendor'), (0, 'Vulnerability found'), (3, 'Vendor announces fix'), (2, 'Communication with vendor'), (4, 'Fix confirmed'), (5, 'Advisory published'), (100, 'Custom Internal Log')])),
                ('message', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsible_disc.vulnerability')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='TextProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('text', models.TextField(help_text='Markdown supported!')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsible_disc.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(max_length=256, upload_to=apps.responsible_disc.models.get_proof_path)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsible_disc.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
