# Generated by Django 4.0.5 on 2022-06-21 04:30

from django.conf import settings
from django.db import migrations
from django.contrib.auth import get_user_model
from guardian.shortcuts import assign_perm


def apply_invite_permissions(apps, schema_editor):
    Vulnerability = apps.get_model('responsible_disc', 'Vulnerability')
    User = get_user_model()
    for vuln in Vulnerability.objects.all():
        user = User.objects.get(pk=vuln.user.pk)
        assign_perm("responsible_disc.invite_vendor", user_or_group=user, obj=vuln)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responsible_disc', '0002_vulnerabilitycomment'),
    ]

    operations = [
        migrations.RunPython(apply_invite_permissions),
    ]
