# Generated by Django 4.0.6 on 2022-07-15 11:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_disc', '0006_vulnerability_advisory_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproof',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='textproof',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
