# Generated by Django 4.0.6 on 2022-07-15 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_disc', '0008_migrate_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproof',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textproof',
            name='id',
        ),
        migrations.AlterField(
            model_name='imageproof',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('40bfd57c-66d1-412a-8f48-e8e0173ebe38'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textproof',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('40bfd57c-66d1-412a-8f48-e8e0173ebe38'), primary_key=True, serialize=False),
        ),
    ]
