# Generated by Django 4.0.6 on 2022-07-15 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('responsible_disc', '0009_remove_imageproof_id_remove_textproof_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproof',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textproof',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
