# Generated by Django 3.2.9 on 2021-12-04 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('os', models.CharField(default='unknown', max_length=28, verbose_name='OS')),
                ('is_online', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('ip', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=12)),
                ('banner', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(default='open', max_length=24)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
            ],
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
            ],
            options={
                'verbose_name_plural': 'Hostnames',
                'unique_together': {('host', 'name')},
            },
        ),
    ]
