# Generated by Django 3.2.9 on 2021-12-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['port'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
