# Generated by Django 3.2.9 on 2021-12-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['-date_updated']},
        ),
    ]
