# Generated by Django 3.2.9 on 2021-12-09 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_parsed_command_commandhistoryitem_command'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networking', '0002_alter_host_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostname',
            name='project',
            field=models.ForeignKey(default='ab9d2293-28ca-4df2-aa97-0496d12c481c', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='project',
            field=models.ForeignKey(default='ab9d2293-28ca-4df2-aa97-0496d12c481c', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
