# Generated by Django 3.2.9 on 2021-12-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0004_auto_20211209_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostname',
            options={'ordering': ['-date_updated'], 'verbose_name_plural': 'Hostnames'},
        ),
    ]
