# Generated by Django 3.2.4 on 2021-06-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pgp_fingerprint',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='PGP-Fingerprint'),
        ),
    ]
