# Generated by Django 3.2.4 on 2021-06-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_pgp_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='Pentester', max_length=32),
        ),
    ]
