# Generated by Django 3.2.4 on 2021-06-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
