# Generated by Django 3.2.12 on 2022-02-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='position',
            field=models.CharField(choices=[('org', 'Organisational'), ('tech', 'Technical')], max_length=64),
        ),
    ]
