# Generated by Django 4.0.6 on 2022-07-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectapitoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cvss_required',
            field=models.BooleanField(default=False, verbose_name='CVSS required'),
        ),
    ]
