# Generated by Django 3.2.12 on 2022-02-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_clientcontact_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
