# Generated by Django 3.2.9 on 2021-12-18 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20211215_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('zip', models.IntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('pgp_key', models.TextField(blank=True, null=True, verbose_name='PGP-Key')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.client')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='report_default_title',
            field=models.CharField(default='Assessment Report', max_length=64),
        ),
        migrations.DeleteModel(
            name='ProjectContact',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default='2c4d70cc-3c4a-46ac-afea-1d55a50f28cb', on_delete=django.db.models.deletion.CASCADE, to='projects.client'),
            preserve_default=False,
        ),
    ]
