# Generated by Django 3.2.9 on 2021-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211218_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            # field=models.CharField(default='DE', max_length=128),
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
    ]
