# Generated by Django 3.2.9 on 2021-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_client_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='position',
            field=models.CharField(max_length=64),
            preserve_default=False,
        ),
    ]
