# Generated by Django 3.2.9 on 2021-12-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_commandhistoryitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandhistoryitem',
            old_name='client',
            new_name='agent',
        ),
    ]
