# Generated by Django 3.2.9 on 2021-12-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_rename_client_commandhistoryitem_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandhistoryitem',
            name='command',
        ),
        migrations.AddField(
            model_name='commandhistoryitem',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
