# Generated by Django 4.0.7 on 2022-08-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['-date_created']},
        ),
    ]
