# Generated by Django 3.2.4 on 2021-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectcontact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
