# Generated by Django 4.0.3 on 2022-04-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_remove_project_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAPIToken',
            fields=[
                ('key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
