# Generated by Django 3.2.9 on 2021-12-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211207_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandhistoryitem',
            old_name='parsed_command',
            new_name='command',
        ),
    ]
