# Generated by Django 3.2.9 on 2021-12-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_parsed_command_commandhistoryitem_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommandHistoryItem',
        ),
    ]
