# Generated by Django 4.0.4 on 2022-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectapitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontributor',
            name='role',
            field=models.CharField(choices=[('pentester', 'Pentester'), ('ro', 'Read Only')], max_length=16),
        ),
    ]
