# Generated by Django 3.2.9 on 2021-12-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_delete_projectmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_default_title',
            field=models.CharField(blank=True, default='Assessment Report', max_length=64),
        ),
    ]
