# Generated by Django 4.0.7 on 2022-10-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectcontact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcontact',
            unique_together={('project', 'client_contact')},
        ),
    ]
