# Generated by Django 4.0.4 on 2022-06-06 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectcontributor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapitoken',
            name='date_valid',
            field=models.DateField(default=datetime.datetime(2022, 6, 6, 14, 10, 35, 775758, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
