# Generated by Django 4.1.2 on 2022-10-07 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_alter_projectcontact_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='customer_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectcontact_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientcontact_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectcontactcreator_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
