# Generated by Django 4.1.2 on 2022-10-07 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_projectcontact_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcontact',
            unique_together={('project', 'customer_contact')},
        ),
        migrations.RemoveField(
            model_name='projectcontact',
            name='client_contact',
        ),
    ]
