# Generated by Django 4.1.2 on 2022-10-08 04:54

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_delete_projectcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.projects.models.customer_logo_upload_path),
        ),
    ]
