# Generated by Django 4.1.2 on 2022-10-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_client_homepage_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontributor',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
