# Generated by Django 3.2.4 on 2021-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='include_watermark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
