# Generated by Django 3.2.4 on 2021-06-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectclassification',
            options={'verbose_name_plural': 'Project Classifications'},
        ),
    ]
