# Generated by Django 4.1.2 on 2022-10-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectcontributor_invite_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cvss_required',
        ),
    ]
