# Generated by Django 3.2.4 on 2021-07-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20210707_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterField(
            model_name='projectclassification',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectcontact',
            name='pgp_fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='PGP-Fingerprint'),
        ),
    ]
