# Generated by Django 3.2.4 on 2021-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectcontact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontact',
            name='pgp_fingerprint',
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='pgp_key',
            field=models.TextField(blank=True, null=True, verbose_name='PGP-Key'),
        ),
    ]
