# Generated by Django 3.2.9 on 2021-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20210708_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_default_title',
            field=models.CharField(default='Pentest Report', max_length=64),
        ),
        migrations.DeleteModel(
            name='ProjectClassification',
        ),
    ]
