# Generated by Django 3.2.9 on 2021-11-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20211128_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
