# Generated by Django 3.2.4 on 2021-06-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcontact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcontact',
            unique_together={('project', 'email')},
        ),
    ]
