# Generated by Django 3.2.4 on 2021-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectcontact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_default_title',
            field=models.CharField(default='Abschlussbericht Penetrationstest', max_length=64),
        ),
    ]
