# Generated by Django 3.2.4 on 2021-06-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210615_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Overwrite Project Title', max_length=64, null=True),
        ),
    ]
