# Generated by Django 3.2.4 on 2021-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_report_custom_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['revision']},
        ),
        migrations.AlterField(
            model_name='report',
            name='latex_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_source',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
