# Generated by Django 3.2.4 on 2021-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210707_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectclassification',
            options={'verbose_name_plural': 'Classifications'},
        ),
    ]
