# Generated by Django 3.2.4 on 2021-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_projectclassification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcontact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
