# This is an example settings file for vulnman


# Enable debug mode. DONT USE IN PRODUCTION ENVIRONMENT!
# DEBUG = True

# Allowed Hosts
# set this to the hostnames of allowed to be used in the Host HTTP header
# ALLOWED_HOSTS = ["vulnman.example.com"]


# CSS theme
# VULNMAN_CSS_THEME = "flatly"

# #################
# Database Settings
# #################
# uncomment the postgres section, if you are using the docker image
#
# Postgres Example:
#
# DATABASES = {
#  'default': {
#    'ENGINE': 'django.db.backends.postgresql',
#    'HOST': 'db',
#    'NAME': 'vulnman',
#    'USER': 'vulnman_db_user',
#    'PASSWORD': 'dontusethispassword',
#  }
# }

# ##############
# External Tools
# ##############
# add your own custom tools classes here
# CUSTOM_EXTERNAL_TOOLS = {
#     "my-new-nmap-parser": "apps.external_tools.parsers.nmap.NmapParser",
# }

# #########
# Reporting
# #########

# Pentest company name
# This name is used in some parts of the reports. This usually is the name of your company.
# REPORT_PENTEST_COMPANY = "Example IT-Sec Ltd."

# Path to the latex interpreter used to generate the reports
# LATEX_INTERPRETER = 'latexmk -pdf'

# Report Template
# REPORT_TEMPLATE = "custom/report/document.tex"

# ########
# Security
# For further harding checks see https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
# Note: the SECRET_KEY value is uniquely auto generated by default for vulnman installations
# ########

# Set this to True to avoid transmitting the CSRF cookie over HTTP accidentally.
CSRF_COOKIE_SECURE = True

# Set this to True to avoid transmitting the session cookie over HTTP accidentally.
SESSION_COOKIE_SECURE = True
