# Generated by Django 4.0.4 on 2022-04-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcondition',
            unique_together={('task', 'asset_type', 'condition')},
        ),
        migrations.RemoveField(
            model_name='taskcondition',
            name='is_regex',
        ),
        migrations.RemoveField(
            model_name='taskcondition',
            name='on_pentest',
        ),
    ]
