# Generated by Django 4.0.4 on 2022-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_taskcondition_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='name',
            field=models.CharField(default='always', max_length=128),
        ),
    ]
