# Generated by Django 4.0.4 on 2022-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskcondition_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcondition',
            unique_together={('task', 'asset_type', 'name', 'condition')},
        ),
    ]
