# Generated by Django 3.2.9 on 2021-12-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20211215_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('revision', models.CharField(default='0.1', help_text='The reports are ordered by revisions', max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('custom_title', models.CharField(blank=True, help_text='Overwrite Project Title', max_length=64, null=True)),
                ('changes', models.CharField(max_length=128)),
                ('raw_source', models.TextField(blank=True, null=True)),
                ('pdf_source', models.BinaryField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('include_watermark', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['revision'],
                'unique_together': {('project', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='ReportShareToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=512)),
                ('date_expires', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.report')),
            ],
        ),
    ]
