# Generated by Django 3.2.9 on 2021-12-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsharetoken',
            name='share_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
