# Generated by Django 3.2.12 on 2022-02-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pentestreport',
            name='mgmt_summary_evalution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pentestreport',
            name='mgmt_summary_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pentestreport',
            name='report_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
