# Generated by Django 3.2.12 on 2022-02-28 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_delete_scope'),
        ('reporting', '0003_rename_mgmt_summary_evalution_pentestreport_mgmt_summary_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pentestreport',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pentestreport',
            name='mgmt_summary_evaluation',
        ),
        migrations.RemoveField(
            model_name='pentestreport',
            name='mgmt_summary_recommendation',
        ),
        migrations.RemoveField(
            model_name='pentestreport',
            name='report_title',
        ),
        migrations.AddField(
            model_name='pentestreport',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportInformation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportinformation_set', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reportinformation_set', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
