# Generated by Django 3.2.9 on 2021-12-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_report_report_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='raw_source',
            new_name='latex_source',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_language',
        ),
    ]
