# Generated by Django 3.2.9 on 2021-12-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_reportsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportsection',
            unique_together={('report', 'order')},
        ),
    ]
