# Generated by Django 3.2.12 on 2022-02-28 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0004_auto_20220228_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinformation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportinformation_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
