# Generated by Django 4.0.5 on 2022-06-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_report_delete_reportconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='Report', max_length=128),
        ),
    ]
