# Generated by Django 4.0.3 on 2022-03-22 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_reportinformation_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportsection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reportsection',
            name='report',
        ),
        migrations.AlterField(
            model_name='pentestreport',
            name='report_type',
            field=models.CharField(choices=[('draft', 'Draft'), ('release', 'Release')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reportsharetoken',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporting.pentestreport'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportSection',
        ),
    ]
