# Generated by Django 4.0.5 on 2022-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_reportrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrelease',
            name='raw_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
