# Generated by Django 3.2.12 on 2022-02-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_pentestreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.pentestreport'),
        ),
    ]
