# Generated by Django 4.0.5 on 2022-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_alter_reportrelease_raw_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.CharField(choices=[('default', 'default')], default='default', max_length=64),
        ),
    ]
