# Generated by Django 4.0.5 on 2022-06-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.PositiveIntegerField(choices=[(0, 'PDF'), (1, 'JSON')], default=0),
        ),
    ]
