# Generated by Django 4.0.5 on 2022-06-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_alter_report_options_delete_pentestreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportrelease',
            options={'ordering': ['-date_created']},
        ),
    ]
