# Generated by Django 4.0.5 on 2022-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_alter_reportrelease_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
