# Generated by Django 4.0.6 on 2022-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0014_remove_report_work_in_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.CharField(choices=[('default', 'default'), ('custom', 'custom')], default='default', max_length=64),
        ),
    ]
