# Generated by Django 4.0.6 on 2022-07-13 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_project_cvss_required'),
        ('reporting', '0015_alter_report_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('version', models.FloatField()),
                ('change', models.PositiveIntegerField(choices=[(0, 'Report created'), (5, 'Added vulnerabilities'), (10, 'Fixed typo'), (20, 'Report finalized')])),
                ('date', models.DateField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
