# Generated by Django 4.0.6 on 2022-07-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_reportversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportversion',
            options={'ordering': ['-version']},
        ),
    ]
