# Generated by Django 4.0.6 on 2022-07-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0017_alter_reportversion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportversion',
            options={'ordering': ['version']},
        ),
        migrations.AddField(
            model_name='reportversion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportversion',
            unique_together={('report', 'version')},
        ),
    ]
