# Generated by Django 4.0.6 on 2022-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_alter_reportversion_options_reportversion_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrelease',
            name='task_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
