# Generated by Django 4.0.7 on 2022-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0019_reportrelease_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.AddField(
            model_name='report',
            name='report_variant',
            field=models.PositiveIntegerField(choices=[(0, 'Pentest Report')], default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(default='Pentest Report', max_length=128),
        ),
    ]
