# Generated by Django 4.0.7 on 2022-09-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_remove_report_report_type_report_report_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_variant',
            field=models.PositiveIntegerField(choices=[(0, 'Pentest Report'), (1, 'Pentest CSV')], default=0),
        ),
    ]
