# Generated by Django 4.0.7 on 2022-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_alter_report_report_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.CharField(choices=[('default', 'default'), ('blockomat', 'blockomat')], default='default', max_length=64),
        ),
    ]
