# Generated by Django 4.0.7 on 2022-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0022_alter_report_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.CharField(choices=[('default', 'default'), ('blockomat', 'blockomat'), ('usdAG', 'usdAG')], default='default', max_length=64),
        ),
    ]
