# Generated by Django 4.1.2 on 2022-10-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_alter_report_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_variant',
            field=models.PositiveIntegerField(choices=[(0, 'Pentest Report'), (1, 'Vulnerability CSV')], default=0),
        ),
    ]
