# Generated by Django 4.1.2 on 2022-12-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_alter_report_report_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='template',
            field=models.CharField(choices=[('default', 'default'), ('blockomat', 'blockomat')], default='default', max_length=64),
        ),
    ]
