<<<<<<< HEAD
# Generated by Django 3.2.10 on 2022-01-30 17:08
=======
# Generated by Django 3.2.12 on 2022-02-23 16:27
>>>>>>> origin/dev

import apps.findings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('projects', '0011_project_name_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('networking', '0002_alter_service_options'),
        ('assets', '0001_initial'),
        ('commands', '0001_initial'),
=======
        ('projects', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/dev
    ]

    operations = [
        migrations.CreateModel(
            name='CWEEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('entry', models.CharField(max_length=32, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('severity', models.PositiveIntegerField(choices=[(4, 'critical'), (3, 'high'), (2, 'medium'), (1, 'low'), (0, 'informational')])),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('vulnerability_id', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['vulnerability_id'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityReference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
<<<<<<< HEAD
                'abstract': False,
=======
                'verbose_name': 'Vulnerability Category',
                'verbose_name_plural': 'Vulnerability Categories',
>>>>>>> origin/dev
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
<<<<<<< HEAD
                ('details', models.TextField(blank=True, help_text='Markdown supported!', null=True)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_vector', models.CharField(blank=True, max_length=64, null=True, verbose_name='CVSS Vector')),
                ('method', models.CharField(blank=True, max_length=12, null=True)),
                ('parameter', models.CharField(blank=True, max_length=128, null=True)),
                ('parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('query_parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('site', models.CharField(blank=True, max_length=256, null=True)),
=======
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_vector', models.CharField(blank=True, max_length=64, null=True, verbose_name='CVSS Vector')),
>>>>>>> origin/dev
                ('cve_id', models.CharField(blank=True, max_length=28, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('false_positive', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('asset_webapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.webapplication')),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.service')),
=======
                ('asset_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.host')),
                ('asset_webapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.webapplication')),
                ('asset_webrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.webrequest')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
>>>>>>> origin/dev
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.template')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-cvss_score', '-verified'],
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='TextProof',
=======
            name='UserAccount',
>>>>>>> origin/dev
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('text', models.TextField(help_text='Markdown supported!')),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
=======
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=512)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('account_compromised', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
>>>>>>> origin/dev
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(to='findings.VulnerabilityCategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='cwe_ids',
            field=models.ManyToManyField(to='findings.CWEEntry'),
        ),
        migrations.CreateModel(
            name='TextProof',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('text', models.TextField(help_text='Markdown supported!')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='template',
            name='categories',
            field=models.ManyToManyField(to='findings.VulnerabilityCategory'),
        ),
        migrations.AddField(
            model_name='template',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='cwe_ids',
            field=models.ManyToManyField(to='findings.CWEEntry'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findings.template')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.CreateModel(
            name='ImageProof',
<<<<<<< HEAD
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(max_length=256, upload_to=apps.findings.models.project_pocs_path)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finding',
=======
>>>>>>> origin/dev
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
<<<<<<< HEAD
                ('data', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('finding_type', models.CharField(choices=[('undefined', 'Undefined'), ('tech', 'Technology'), ('url', 'URL')], default='undefined', max_length=32)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
=======
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(max_length=256, upload_to=apps.findings.models.project_pocs_path)),
>>>>>>> origin/dev
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
