# Generated by Django 3.2.9 on 2021-12-15 08:01

import apps.findings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commands', '0001_initial'),
        ('networking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20211215_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Markdown supported!')),
                ('resolution', models.TextField(help_text='Markdown supported')),
                ('ease_of_resolution', models.CharField(choices=[('undetermined', 'Undetermined'), ('trivial', 'Trivial'), ('simple', 'Simple'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('infeasible', 'Infeasible')], max_length=32)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_updated'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Markdown supported!')),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_vector', models.CharField(blank=True, max_length=64, null=True, verbose_name='CVSS Vector')),
                ('resolution', models.TextField(blank=True, help_text='Markdown supported', null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('ease_of_resolution', models.CharField(choices=[('undetermined', 'Undetermined'), ('trivial', 'Trivial'), ('simple', 'Simple'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('infeasible', 'Infeasible')], max_length=32)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.service')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-cvss_score'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(help_text='Markdown supported!')),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=12, null=True)),
                ('parameter', models.CharField(blank=True, max_length=128, null=True)),
                ('parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('path', models.CharField(blank=True, max_length=256, null=True)),
                ('query_parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('site', models.CharField(blank=True, max_length=256, null=True)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findings.template')),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findings.template')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofOfConcept',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.findings.models.project_pocs_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Proof of Concept',
                'verbose_name_plural': 'Proof of Concepts',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('data', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
                ('hostname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.hostname')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.service')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
