# Generated by Django 3.2.9 on 2021-12-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
