# Generated by Django 3.2.12 on 2022-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_alter_imageproof_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ['-cvss_score'], 'verbose_name': 'Vulnerability', 'verbose_name_plural': 'Vulnerabilities'},
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='false_positive',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='is_fixed',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='verified',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (2, 'Verified'), (1, 'Fixed')], default=0),
        ),
    ]
