# Generated by Django 3.2.9 on 2021-12-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_template_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('name',)},
        ),
    ]
