# Generated by Django 3.2.9 on 2021-12-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_alter_vulnerabilitydetails_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='finding_type',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('tech', 'Technology'), ('url', 'URL')], default='undefined', max_length=32),
        ),
    ]
