# Generated by Django 4.0.5 on 2022-06-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_remove_vulnerabilitycategory_name_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='name_de',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='recommendation_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='recommendation_en',
            field=models.TextField(null=True),
        ),
    ]
