# Generated by Django 3.2.9 on 2021-12-10 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0005_alter_hostname_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_alter_projectmember_options'),
        ('findings', '0004_auto_20211210_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Markdown supported!')),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_vector', models.CharField(blank=True, max_length=64, null=True, verbose_name='CVSS Vector')),
                ('resolution', models.TextField(blank=True, help_text='Markdown supported', null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('ease_of_resolution', models.CharField(choices=[('undetermined', 'Undetermined'), ('trivial', 'Trivial'), ('simple', 'Simple'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('infeasible', 'Infeasible')], max_length=32)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.service')),
            ],
            options={
                'ordering': ['-cvss_score'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(help_text='Markdown supported!')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='finding',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='host',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='project',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='finding',
        ),
        migrations.RemoveField(
            model_name='template',
            name='references',
        ),
        migrations.DeleteModel(
            name='FindingDetails',
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findings.template'),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='vulnerability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability'),
        ),
        migrations.AddField(
            model_name='reference',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability'),
        ),
        migrations.AlterField(
            model_name='proofofconcept',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability'),
        ),
        migrations.DeleteModel(
            name='Finding',
        ),
    ]
