# Generated by Django 3.2.9 on 2021-12-10 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0005_alter_hostname_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_alter_projectmember_options'),
        ('findings', '0005_auto_20211210_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('data', models.TextField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('steps_to_reproduce', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.service')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
