# Generated by Django 3.2.12 on 2022-02-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='details',
        ),
        migrations.DeleteModel(
            name='Finding',
        ),
    ]
