# Generated by Django 3.2.12 on 2022-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0006_auto_20220220_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
