# Generated by Django 3.2.9 on 2021-12-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0005_alter_hostname_options'),
        ('findings', '0006_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.hostname'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.host'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.service'),
        ),
    ]
