# Generated by Django 3.2.9 on 2021-12-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0007_auto_20211210_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ['-cvss_score'], 'verbose_name': 'Vulnerability', 'verbose_name_plural': 'Vulnerabilities'},
        ),
        migrations.RemoveField(
            model_name='reference',
            name='project',
        ),
    ]
