# Generated by Django 3.2.9 on 2021-12-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0007_alter_vulnerabilitydetails_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='vulnerability',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='cve_id',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='ease_of_resolution',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='resolution',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='method',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='parameter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='parameters',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='query_parameters',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='site',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.template'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VulnerabilityDetails',
        ),
    ]
