# Generated by Django 3.2.9 on 2021-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0008_auto_20211220_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='cve_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CVE ID'),
        ),
    ]
