# Generated by Django 3.2.9 on 2021-12-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0008_auto_20211210_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='method',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='parameter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='parameters',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='query_parameters',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilitydetails',
            name='site',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
