# Generated by Django 4.0.7 on 2022-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0009_vulnerability_findings_vu_content_d4ec3e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
