# Generated by Django 3.2.9 on 2021-12-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0011_vulnerability_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofconcept',
            name='is_code',
            field=models.BooleanField(default=False),
        ),
    ]
