# Generated by Django 4.1.2 on 2022-10-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0012_owaspscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owaspscore',
            name='skills_required',
            field=models.PositiveIntegerField(choices=[(0, 'Not Applicable (0)'), (1, 'Security Penetration Skills (1)'), (3, 'Networking And Programming Skills (3)'), (4, 'Advanced Computer User (4)'), (6, 'Some Technical Skills (6)'), (9, 'No Technical Skills (9)')], help_text='How technically skilled is this group of threat agents?'),
        ),
    ]
