# Generated by Django 3.2.9 on 2021-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0013_vulnerability_exclude_from_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
