# Generated by Django 4.1.2 on 2022-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0014_alter_owaspscore_motive_alter_owaspscore_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owaspscore',
            name='awareness',
            field=models.PositiveIntegerField(choices=[(0, 'Not Applicable (0)'), (1, 'Unknown (1)'), (4, 'Hidden (4)'), (6, 'Obvious (6)'), (9, 'Public Knowledge (9)')], help_text='How well known is this vulnerability to this group of threat agents?'),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='ease_of_discovery',
            field=models.PositiveIntegerField(choices=[(0, 'Not Applicable (0)'), (1, 'Practically impossible (1)'), (3, 'Difficult (3)'), (7, 'Easy (7)'), (9, 'Automated Tools Available (9)')], help_text='How easy is it for this group of threat agents to discover this vulnerability? '),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='ease_of_exploit',
            field=models.PositiveIntegerField(choices=[(0, 'Not Applicable (0)'), (1, 'Theoretical (1)'), (3, 'Difficult (3)'), (5, 'Easy (5)'), (9, 'Automated Tools Available (9)')], help_text='How easy is it for this group of threat agents to actually exploit this vulnerability? '),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='intrusion_detection',
            field=models.PositiveIntegerField(choices=[(0, 'Not Applicable (0)'), (1, 'Active detection in application (1)'), (3, 'Logged and reviewed (3)'), (8, 'Logged without review (8)'), (9, 'Not logged (9)')], help_text='How likely is an exploit to be detected?'),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='loss_of_accountability',
            field=models.PositiveIntegerField(choices=[(1, 'Fully traceable (1)'), (7, 'Possibly traceable (7)'), (9, 'Completely anonymous (9)')], help_text='Are the threat agents’ actions traceable to an individual?'),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='loss_of_availability',
            field=models.PositiveIntegerField(choices=[(1, 'Minimal secondary services interrupted (1)'), (5, 'Minimal primary services interrupted (5)'), (5, 'Extensive secondary services interrupted (5)'), (7, 'Extensive primary services interrupted (7)'), (9, 'All services completely list (9)')], help_text='How much service could be lost and how vital is it?'),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='loss_of_confidentiality',
            field=models.PositiveIntegerField(choices=[(2, 'Minimal non-sensitive data disclosed (2)'), (6, 'Minimal critical data disclosed (6)'), (6, 'Extensive non-sensitive data disclosed (6)'), (7, 'Extensive critical data disclosed (7)'), (9, 'All data disclosed (9)')], help_text='How much data could be disclosed and how sensitive is it?'),
        ),
        migrations.AlterField(
            model_name='owaspscore',
            name='loss_of_integrity',
            field=models.PositiveIntegerField(choices=[(1, 'Minimal slightly corrupt data (1)'), (3, 'Minimal seriously corrupt data (3)'), (5, 'Extensive slightly corrupt data (5)'), (7, 'Extensive seriously corrupt data (7)'), (9, 'All data totally corrupt (9)')], help_text='How much data could be corrupted and how damaged is it?'),
        ),
    ]
