# Generated by Django 4.0.4 on 2022-04-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0016_template_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='categories',
        ),
    ]
