# Generated by Django 4.1.2 on 2022-10-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0017_cvsscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
