# Generated by Django 4.0.4 on 2022-04-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0017_remove_template_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='findings.vulnerabilitycategory'),
        ),
    ]
