# Generated by Django 3.2.11 on 2022-01-28 16:07

import apps.findings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
        ('projects', '0010_alter_clientcontact_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('findings', '0020_vulnerability_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='active',
        ),
        migrations.CreateModel(
            name='TextProof',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('text', models.TextField(help_text='Markdown supported!')),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageProof',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(max_length=256, upload_to=apps.findings.models.project_pocs_path)),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findings.vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
