# Generated by Django 4.0.4 on 2022-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0020_alter_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
