# Generated by Django 3.2.10 on 2022-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0021_auto_20220128_1607'),
        ('findings', '0021_vulnerability_cve_id'),
    ]

    operations = [
    ]
