# Generated by Django 3.2.10 on 2022-01-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0022_merge_20220128_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProofOfConcept',
        ),
    ]
