# Generated by Django 3.2.9 on 2021-12-04 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vulns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapps', '0001_initial'),
        ('projects', '0001_initial'),
        ('networking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApplicationUrlPath',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512, unique=True)),
                ('full_url', models.URLField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.hostname')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networking.service')),
                ('web_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapps.webapplication')),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField()),
                ('impact', models.TextField()),
                ('references', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(help_text='Markdown supported')),
                ('cvss_string', models.CharField(blank=True, max_length=64, null=True, verbose_name='CVSS Vector')),
                ('cvss_base_score', models.FloatField(blank=True, null=True)),
                ('impact', models.TextField()),
                ('remediation', models.TextField()),
                ('is_fixed', models.BooleanField(default=False)),
                ('references', models.TextField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='networking.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('vulnerability_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vulns.vulnerabilitytemplate')),
            ],
            options={
                'ordering': ['-cvss_base_score'],
            },
        ),
        migrations.CreateModel(
            name='ProofOfConcept',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to=vulns.models.project_pocs_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerability')),
            ],
            options={
                'verbose_name': 'Proof of Concept',
                'verbose_name_plural': 'Proof of Concepts',
            },
        ),
    ]
