# Generated by Django 3.2.9 on 2021-12-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_auto_20211206_1249'),
        ('vulns', '0003_alter_vulnerabilitytemplate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='findings.template'),
        ),
        migrations.DeleteModel(
            name='VulnerabilityTemplate',
        ),
    ]
