# Generated by Django 3.2.4 on 2021-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0003_auto_20210615_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(default='unknown', max_length=28, verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
