# Generated by Django 3.2.4 on 2021-06-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210615_1340'),
        ('vulns', '0004_auto_20210616_0651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('ip', 'project')},
        ),
    ]
