# Generated by Django 3.2.4 on 2021-06-16 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vulns.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns', '0006_vulnerability_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfConcept',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('file', models.FileField(blank=True, upload_to=vulns.models.project_pocs_path)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
