# Generated by Django 3.2.4 on 2021-06-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0007_proofofconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofconcept',
            name='vuln',
            field=models.ForeignKey(default='affc3876-37da-4abb-8014-2bccc30f79bb', on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerability'),
            preserve_default=False,
        ),
    ]
