# Generated by Django 3.2.4 on 2021-06-16 10:14

from django.db import migrations, models
import vulns.models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0009_remove_vulnerability_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proofofconcept',
            name='file',
        ),
        migrations.AddField(
            model_name='proofofconcept',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofofconcept',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vulns.models.project_pocs_path),
        ),
    ]
