# Generated by Django 3.2.4 on 2021-06-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0010_auto_20210616_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proofofconcept',
            options={'verbose_name': 'Proof of Concept', 'verbose_name_plural': 'Proof of Concepts'},
        ),
    ]
