# Generated by Django 3.2.4 on 2021-06-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0012_vulnerability_is_fixed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostname',
            options={'verbose_name_plural': 'Hostnames'},
        ),
        migrations.AlterUniqueTogether(
            name='hostname',
            unique_together={('host', 'name')},
        ),
    ]
