# Generated by Django 3.2.4 on 2021-06-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0015_auto_20210618_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
