# Generated by Django 3.2.4 on 2021-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0020_vulnerability_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(blank=True, help_text='This field is overwritten, if you use a template', null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='references',
            field=models.CharField(blank=True, help_text='comma separated list of references', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(blank=True, help_text='This field is overwritten, if you use a template', null=True),
        ),
    ]
