# Generated by Django 3.2.4 on 2021-06-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0021_auto_20210621_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='references',
            field=models.CharField(blank=True, help_text='This field is overwritten, if you use a template.Comma separated list of references', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerabilitytemplate'),
        ),
    ]
