# Generated by Django 3.2.4 on 2021-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0022_auto_20210621_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='template',
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='references',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(),
        ),
    ]
