# Generated by Django 3.2.4 on 2021-07-09 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns', '0027_alter_vulnerabilitytemplate_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='references',
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vulnerabilitytemplate',
            name='references',
            field=models.ManyToManyField(to='vulns.References'),
        ),
    ]
