# Generated by Django 3.2.4 on 2021-07-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0029_remove_vulnerabilitytemplate_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='references',
        ),
        migrations.AddField(
            model_name='references',
            name='vulnerability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='references',
            name='vulnerability_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerabilitytemplate'),
            preserve_default=False,
        ),
    ]
