# Generated by Django 3.2.4 on 2021-07-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0030_auto_20210709_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='references',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AlterUniqueTogether(
            name='references',
            unique_together={('name', 'vulnerability', 'vulnerability_template')},
        ),
    ]
