# Generated by Django 3.2.4 on 2021-07-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0031_auto_20210709_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='vulnerability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerability'),
        ),
        migrations.AlterField(
            model_name='references',
            name='vulnerability_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vulns.vulnerabilitytemplate'),
        ),
    ]
