# Generated by Django 3.2.4 on 2021-07-09 06:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vulns', '0032_auto_20210709_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='References',
            new_name='Reference',
        ),
    ]
