# Generated by Django 3.2.4 on 2021-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0034_delete_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='references',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vulnerabilitytemplate',
            name='references',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
