# Generated by Django 3.2.9 on 2021-11-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0036_vulnerabilitytemplate_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='banner',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
