# Generated by Django 3.2.9 on 2021-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0037_service_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='up', max_length=24),
        ),
    ]
