# Generated by Django 3.2.9 on 2021-11-29 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0040_webapplicationurlpath_webapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webapplication',
            old_name='name',
            new_name='url_path',
        ),
    ]
