# Generated by Django 3.2.9 on 2021-11-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0041_rename_name_webapplication_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapplication',
            name='url_path',
            field=models.CharField(max_length=512),
        ),
    ]
