# Generated by Django 3.2.9 on 2021-11-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0042_alter_webapplication_url_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
