# Generated by Django 3.2.9 on 2021-11-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0043_webapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='host',
            field=models.ForeignKey(default='39d36779-024b-4138-99d8-b4d56598d190', on_delete=django.db.models.deletion.CASCADE, to='vulns.host'),
            preserve_default=False,
        ),
    ]
