# Generated by Django 3.2.9 on 2021-11-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0044_webapplication_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webapplication',
            name='host',
        ),
        migrations.AddField(
            model_name='webapplication',
            name='hostname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vulns.hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='service',
            field=models.ForeignKey(default='0f49a3b0-7f53-485a-8320-41aee9ad43bd', on_delete=django.db.models.deletion.CASCADE, to='vulns.service'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WebApplicationUrlPath',
        ),
    ]
