# Generated by Django 3.2.9 on 2021-11-29 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_auto_20211128_1835'),
        ('vulns', '0045_auto_20211129_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapplication',
            name='url_path',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.CreateModel(
            name='WebApplicationUrlPath',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512)),
                ('full_url', models.URLField(max_length=512)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulns.hostname')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulns.service')),
            ],
        ),
    ]
