# Generated by Django 3.2.9 on 2021-11-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0047_webapplicationurlpath_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplicationurlpath',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
    ]
