# Generated by Django 3.2.9 on 2021-11-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0048_webapplicationurlpath_status_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebApplication',
        ),
    ]
