# Generated by Django 3.2.9 on 2021-11-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20211128_1835'),
        ('vulns', '0050_webapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='project',
            field=models.ForeignKey(default='9869c1c7-374e-4129-9ee2-ba61ec7f49cb', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
