# Generated by Django 3.2.9 on 2021-11-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0051_webapplication_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplicationurlpath',
            name='web_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vulns.webapplication'),
        ),
    ]
