# Generated by Django 3.2.9 on 2021-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0052_webapplicationurlpath_web_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapplicationurlpath',
            name='full_url',
            field=models.URLField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='webapplicationurlpath',
            name='path',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
