# Generated by Django 3.2.9 on 2021-11-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0054_auto_20211129_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(default='up', max_length=12),
        ),
    ]
