# Generated by Django 3.2.9 on 2021-11-29 19:42

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0057_alter_vulnerability_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='description',
            field=martor.models.MartorField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='impact',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='references',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='remediation',
            field=martor.models.MartorField(),
        ),
    ]
