# Generated by Django 3.2.9 on 2021-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0058_auto_20211129_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='impact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='remediation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='impact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='references',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilitytemplate',
            name='remediation',
            field=models.TextField(),
        ),
    ]
