# Generated by Django 3.2.9 on 2021-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0059_auto_20211129_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
        migrations.AddField(
            model_name='host',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
