# Generated by Django 3.2.9 on 2021-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0060_auto_20211129_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(default='open', max_length=24),
        ),
    ]
