# Generated by Django 3.2.9 on 2021-12-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0061_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilitytemplate',
            name='exploitation',
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(help_text='Markdown supported'),
        ),
    ]
