# Generated by Django 4.1.2 on 2022-10-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_projecttask_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('task', 'on_asset_type', 'name', 'value')},
        ),
        migrations.AddField(
            model_name='condition',
            name='on_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='condition',
            name='on_asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('host', 'Host'), ('service', 'Service'), ('network', 'Network')], max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('task', 'on_project'), ('task', 'on_asset_type', 'name', 'value')},
        ),
    ]
