# Generated by Django 4.1.2 on 2022-10-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_condition_unique_together_condition_on_project_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('task', 'on_asset_type', 'name', 'value')},
        ),
        migrations.RemoveField(
            model_name='condition',
            name='on_project',
        ),
    ]
