# Generated by Django 4.1.2 on 2022-10-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('checklists', '0005_alter_projecttask_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['Host', 'Service', 'assets.WebApplication']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
