# Generated by Django 4.1.2 on 2022-10-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_alter_projecttask_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='on_asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('host', 'Host'), ('service', 'Service'), ('network', 'Network'), ('thickclient', 'Thick-Client')], max_length=128),
        ),
    ]
