# Generated by Django 4.1.2 on 2022-10-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_alter_condition_on_asset_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='projecttask',
            unique_together={('task_id', 'object_id')},
        ),
    ]
