# Generated by Django 4.1.2 on 2022-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_alter_projecttask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('host', 'Host'), ('service', 'Service'), ('thick-client', 'Thick Client')], default='webapplication', max_length=64),
        ),
    ]
