# Generated by Django 3.2.9 on 2021-11-25 12:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0021_auto_20210708_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('cleartext_password', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=512)),
                ('location_found', models.CharField(max_length=512)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
