# Generated by Django 3.2.9 on 2021-12-15 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=28)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentQueue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('command', models.TextField()),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('execution_started', models.DateTimeField(blank=True, null=True)),
                ('execution_ended', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
