# Generated by Django 3.2.9 on 2021-12-07 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
        ('projects', '0004_commandhistoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentqueue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.commandhistoryitem'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
