# Generated by Django 3.2.9 on 2021-12-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentqueue',
            name='item',
        ),
    ]
