# Generated by Django 3.2.9 on 2021-12-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agentqueue_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentqueue',
            old_name='parsed_command',
            new_name='command',
        ),
        migrations.AddField(
            model_name='agentqueue',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentqueue',
            name='exit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentqueue',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
