# Generated by Django 3.2.9 on 2021-12-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentqueue_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentqueue',
            name='execution_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentqueue',
            name='execution_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
