# Generated by Django 3.2.12 on 2022-02-23 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgp_fingerprint', models.CharField(blank=True, max_length=256, null=True, verbose_name='PGP-Fingerprint')),
                ('position', models.CharField(default='Pentester', help_text='Position mentioned in report', max_length=32)),
                ('hide_name_in_report', models.BooleanField(default=False, help_text='Use username in report instead of real name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
