# Generated by Django 4.0.3 on 2022-04-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pgp_fingerprint',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
