# Generated by Django 3.2.9 on 2021-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_name_in_report',
            field=models.BooleanField(default=False, help_text='Use username in report instead of real name'),
        ),
    ]
