# Generated by Django 4.0.7 on 2022-08-31 10:55

from django.db import migrations, models


def migrate_user_roles(apps, schema_editor):
    User = apps.get_model('account', 'User')
    for user in User.objects.all():
        if user.is_pentester:
            user.user_role = 0
        elif user.is_customer:
            user.user_role = 2
        elif user.is_vendor:
            user.user_role = 1
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_pentesterprofile_rd_advisory_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.PositiveIntegerField(choices=[(0, 'Pentester'), (2, 'Customer'), (1, 'Vendor')], null=True),
        ),
        migrations.RunPython(migrate_user_roles)
    ]
