# Generated by Django 4.0.5 on 2022-06-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('in_pentest_report', models.BooleanField(blank=True, default=True)),
                ('ip', models.GenericIPAddressField()),
                ('operating_system', models.CharField(blank=True, max_length=256)),
                ('accessibility', models.IntegerField(choices=[(1, 'Accessible'), (2, 'Not Accessible'), (0, 'Not Tested')], default=0)),
                ('dns', models.CharField(blank=True, max_length=256, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['ip'],
                'unique_together': {('project', 'ip')},
            },
        ),
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('in_pentest_report', models.BooleanField(blank=True, default=True)),
                ('name', models.CharField(max_length=256)),
                ('base_url', models.URLField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Web Application',
                'verbose_name_plural': 'Web Applications',
            },
        ),
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('in_pentest_report', models.BooleanField(blank=True, default=True)),
                ('url', models.URLField(blank=True)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('web_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.webapplication')),
            ],
            options={
                'verbose_name': 'Web Request',
                'verbose_name_plural': 'Web Requests',
                'unique_together': {('web_app', 'url', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('in_pentest_report', models.BooleanField(blank=True, default=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=12)),
                ('state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('filtered', 'Filtered')], default='filtered', max_length=24)),
                ('banner', models.CharField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'host', 'port', 'protocol')},
            },
        ),
    ]
