# Generated by Django 3.2.12 on 2022-02-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webapplication',
            options={'verbose_name': 'Web Application', 'verbose_name_plural': 'Web Applications'},
        ),
    ]
