# Generated by Django 3.2.12 on 2022-02-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
