# Generated by Django 4.0.6 on 2022-07-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='dns',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='DNS'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=models.CharField(blank=True, max_length=256, verbose_name='Operating System'),
        ),
    ]
