# Generated by Django 3.2.12 on 2022-02-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_webapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webrequest',
            options={'verbose_name': 'Web Request', 'verbose_name_plural': 'Web Requests'},
        ),
    ]
