# Generated by Django 4.0.3 on 2022-03-22 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_alter_host_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('in_pentest_report', models.BooleanField(blank=True, default=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=12)),
                ('state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('filtered', 'Filtered')], default='filtered', max_length=24)),
                ('banner', models.CharField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.host')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'host', 'port', 'protocol')},
            },
        ),
    ]
