# Generated by Django 4.0.6 on 2022-07-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_host_dns_alter_host_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hide_from_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='hide_from_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webapplication',
            name='hide_from_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webrequest',
            name='hide_from_report',
            field=models.BooleanField(default=False),
        ),
    ]
