# Generated by Django 3.2.12 on 2022-02-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_webrequest_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webrequest',
            unique_together={('web_app', 'url', 'parameter')},
        ),
    ]
