# Generated by Django 4.0.3 on 2022-04-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.host'),
        ),
    ]
