# Generated by Django 4.0.6 on 2022-08-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_host_in_pentest_report_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='webapplication',
            options={'ordering': ['-date_created'], 'verbose_name': 'Web Application', 'verbose_name_plural': 'Web Applications'},
        ),
        migrations.AlterModelOptions(
            name='webrequest',
            options={'ordering': ['-date_created'], 'verbose_name': 'Web Request', 'verbose_name_plural': 'Web Requests'},
        ),
    ]
