# Generated by Django 4.0.7 on 2022-08-23 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_clientcontact_position'),
        ('assets', '0005_alter_service_options_alter_webapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebURL',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('hide_from_report', models.BooleanField(default=False)),
                ('path', models.CharField(max_length=512)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.webapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
