# Generated by Django 4.0.7 on 2022-08-25 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_webrequest_unique_together_and_more'),
        ('methodologies', '0004_alter_assettask_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebRequest',
        ),
        migrations.DeleteModel(
            name='WebURL',
        ),
    ]
