# Generated by Django 4.0.7 on 2022-08-25 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_clientcontact_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0008_delete_webrequest_delete_weburl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('hide_from_report', models.BooleanField(default=False)),
                ('accessibility', models.IntegerField(choices=[(1, 'Accessible'), (2, 'Not Accessible'), (0, 'Not Tested')], default=0)),
                ('name', models.CharField(max_length=64)),
                ('start_ip', models.GenericIPAddressField(verbose_name='Start-IP')),
                ('network_mask', models.IntegerField()),
                ('vlan', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
