# Generated by Django 4.0.7 on 2022-08-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='environment',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (2, 'Production'), (1, 'Testing'), (4, 'Development'), (3, 'Staging')], default=0),
        ),
        migrations.AddField(
            model_name='webapplication',
            name='environment',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (2, 'Production'), (1, 'Testing'), (4, 'Development'), (3, 'Staging')], default=0),
        ),
    ]
