# Generated by Django 4.0.7 on 2022-08-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_clientcontact_position'),
        ('assets', '0010_host_environment_webapplication_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('hide_from_report', models.BooleanField(default=False)),
                ('accessibility', models.IntegerField(choices=[(1, 'Accessible'), (2, 'Not Accessible'), (0, 'Not Tested')], default=0)),
                ('url', models.URLField(blank=True)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('web_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.webapplication')),
            ],
            options={
                'verbose_name': 'Web Request',
                'verbose_name_plural': 'Web Requests',
                'ordering': ['-date_created'],
                'unique_together': {('web_app', 'url', 'parameter')},
            },
        ),
    ]
