# Generated by Django 4.0.7 on 2022-09-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_webrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebRequest',
        ),
    ]
