# Generated by Django 4.1.2 on 2022-10-21 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_projectcontributor_invite_email_and_more'),
        ('assets', '0012_delete_webrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThickClient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('hide_from_report', models.BooleanField(default=False)),
                ('accessibility', models.IntegerField(choices=[(1, 'Accessible'), (2, 'Not Accessible'), (0, 'Not Tested')], default=0)),
                ('name', models.CharField(max_length=128)),
                ('programming_language', models.CharField(blank=True, max_length=32, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=256, verbose_name='Operating System')),
                ('environment', models.PositiveIntegerField(choices=[(0, 'Unknown'), (2, 'Production'), (1, 'Testing'), (4, 'Development'), (3, 'Staging')], default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-date_updated'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
