# Generated by Django 3.2.12 on 2022-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='task',
            name='methodology',
        ),
    ]
