# Generated by Django 4.0.7 on 2022-08-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcondition',
            name='asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('webrequest', 'URL'), ('host', 'Host'), ('service', 'Service')], max_length=128),
        ),
    ]
