# Generated by Django 3.2.12 on 2022-02-24 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('methodologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCondition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('webapplication', 'Web Application'), ('webrequest', 'Web Request')], max_length=128)),
                ('condition', models.CharField(max_length=256)),
                ('is_regex', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodologies.task')),
            ],
            options={
                'unique_together': {('task', 'asset_type', 'condition', 'is_regex')},
            },
        ),
    ]
