# Generated by Django 3.2.9 on 2021-12-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodology',
            name='suggested_commands',
        ),
        migrations.AddField(
            model_name='suggestedcommand',
            name='methodology',
            field=models.ForeignKey(default='2e74ee91-399b-47af-9fbc-4e7796241541', on_delete=django.db.models.deletion.CASCADE, to='methodologies.methodology'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suggestedcommand',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
