# Generated by Django 3.2.9 on 2021-12-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0002_auto_20211202_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestedcommand',
            options={'verbose_name': 'Suggested Command', 'verbose_name_plural': 'Suggested Commands'},
        ),
        migrations.AlterUniqueTogether(
            name='suggestedcommand',
            unique_together={('methodology', 'name')},
        ),
    ]
