# Generated by Django 3.2.12 on 2022-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0002_auto_20220221_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('task_id',)},
        ),
    ]
