# Generated by Django 4.0.7 on 2022-08-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0002_alter_taskcondition_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcondition',
            name='asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('webrequest', 'Web Request'), ('host', 'Host'), ('service', 'Service'), ('weburl', 'URL')], max_length=128),
        ),
    ]
