# Generated by Django 3.2.9 on 2021-12-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0003_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodology',
            options={'ordering': ['-date_updated']},
        ),
        migrations.DeleteModel(
            name='SuggestedCommand',
        ),
    ]
