# Generated by Django 3.2.12 on 2022-02-21 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_webrequest_unique_together'),
        ('commands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_project_name_2'),
        ('methodologies', '0003_auto_20220221_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('asset_webapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.webapplication')),
                ('asset_webrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.webrequest')),
                ('command_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.commandhistoryitem')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectmethodology',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectmethodology',
            name='command_created',
        ),
        migrations.RemoveField(
            model_name='projectmethodology',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='projectmethodology',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='projecttask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='command_created',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Methodology',
        ),
        migrations.DeleteModel(
            name='ProjectMethodology',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
        migrations.AddField(
            model_name='assettask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodologies.task'),
        ),
        migrations.AlterUniqueTogether(
            name='assettask',
            unique_together={('task', 'asset_webapp', 'asset_webrequest')},
        ),
    ]
