# Generated by Django 4.0.7 on 2022-08-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_clientcontact_position'),
        ('assets', '0007_alter_webrequest_unique_together_and_more'),
        ('methodologies', '0003_alter_taskcondition_asset_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assettask',
            unique_together={('task', 'project', 'asset_webapp'), ('task', 'project', 'asset_host'), ('task', 'project', 'asset_service')},
        ),
        migrations.AlterField(
            model_name='taskcondition',
            name='asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('host', 'Host'), ('service', 'Service')], max_length=128),
        ),
        migrations.RemoveField(
            model_name='assettask',
            name='asset_webrequest',
        ),
    ]
