# Generated by Django 4.0.7 on 2022-08-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0004_alter_assettask_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcondition',
            name='asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('host', 'Host'), ('service', 'Service'), ('network', 'Network')], max_length=128),
        ),
    ]
