# Generated by Django 3.2.12 on 2022-02-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_name_2'),
        ('assets', '0004_alter_webrequest_unique_together'),
        ('methodologies', '0004_auto_20220221_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assettask',
            unique_together={('task', 'project', 'asset_webapp'), ('task', 'project', 'asset_webrequest')},
        ),
    ]
