# Generated by Django 3.2.12 on 2022-02-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_host_description'),
        ('methodologies', '0004_taskcondition_on_pentest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettask',
            name='asset_webapp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.webapplication'),
        ),
        migrations.AlterField(
            model_name='assettask',
            name='asset_webrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.webrequest'),
        ),
    ]
