# Generated by Django 3.2.12 on 2022-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodologies', '0005_auto_20220225_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcondition',
            name='asset_type',
            field=models.CharField(choices=[('webapplication', 'Web Application'), ('webrequest', 'Web Request'), ('host', 'Host')], max_length=128),
        ),
    ]
