# Generated by Django 4.0.4 on 2022-04-17 07:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectapitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_alter_service_host'),
        ('methodologies', '0007_alter_taskcondition_asset_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetTask',
            new_name='AssetTask2',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Task2',
        ),
        migrations.RenameModel(
            old_name='TaskCondition',
            new_name='TaskCondition2',
        ),
    ]
