# Generated by Django 3.2.9 on 2021-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='cleartext_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
