# Generated by Django 3.2.9 on 2021-12-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20211206_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Credential', 'verbose_name_plural': 'Credentials'},
        ),
        migrations.AlterField(
            model_name='credential',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.employee'),
        ),
    ]
