# Generated by Django 3.2.9 on 2021-12-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_alter_host_options'),
        ('social', '0004_auto_20211207_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='valid_services',
            field=models.ManyToManyField(blank=True, null=True, to='networking.Service'),
        ),
    ]
