# Generated by Django 3.2.9 on 2021-12-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_alter_host_options'),
        ('social', '0005_alter_credential_valid_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='valid_services',
            field=models.ManyToManyField(blank=True, to='networking.Service'),
        ),
    ]
