# Generated by Django 3.2.9 on 2021-12-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_credential_valid_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-date_updated']},
        ),
    ]
